name: rbe-502

# Before running any of these services, run 'xhost +local:' to allow
# connections to the host x server from the container.

services:
  sim:
    image: ros2-gazebo:latest
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    # give the container a command to keep it up without doing any useful work
    #command: /bin/sh -c 'gz sim'

# docker run -it --net host -e DISPLAY=${DISPLAY} --volume /tmp/.X11-unix:/tmp/.X11-unix
# docker exec -it

# USERNAME=ros USER_UID=10 USER_GID=10
# groupadd --gid  $USERNAME \
#   && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME \
#   && apt-get update \
#   && apt-get install -y sudo \
#   && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME\
#   && chmod 0440 /etc/sudoers.d/$USERNAME

# useradd ros \
# && apt-get install -y sudo \
# && echo "ros ALL=\(root\) NOPASSWD:ALL" > /etc/sudoers.d/ros \
# && chmod 0440 /etc/sudoers.d/ros

# Refs:
# - GUI with docker: https://www.howtogeek.com/devops/how-to-run-gui-applications-in-a-docker-container/
